In [51]:
price = 3.4
quantity = 30
discount_code = 'SAVE10'

total_cost = price * quantity

if total_cost > 100 and discount_code:
      print('Discount applied!')
else:
      print('No discount')

Discount applied!


In [52]:
orders = [250, 100, -40, 300, 0, 120]
valid_orders = 0
total_value = 0

for order in orders:
      if order < 0:
            continue
      elif order == 0:
            break
      elif order > 0:
            valid_orders += 1
            total_value += order

print(f'Total value: {total_value},  Total cost: {valid_orders}.')

Total value: 650,  Total cost: 3.


In [53]:
orders = [250, 100, -40, 300, 0, 120]
valid_orders = 0
total_value = 0
i = 0

while i < len(orders):
      if orders[i] < 0:
            i += 1
            continue
      elif orders[i] == 0:
            break
      else:
            valid_orders += 1
            total_value += orders[i]
      i += 1

print(f'Total value: {total_value},  Total cost: {valid_orders}.')

Total value: 650,  Total cost: 3.


In [54]:
# You need to produce a cleaned list where:
# Emails are lowercased.
# Leading/trailing spaces are removed.
# Empty strings and None values are removed entirely.
# No duplicates (hint: order should be preserved).

raw_emails = [
    " alice@example.com  ", 
    "BOB@EXAMPLE.COM", 
    "", 
    "carol@example.com", 
    "BOB@EXAMPLE.COM", 
    None, 
    "dan@EXAMPLE.com   "
]

cleaned_emails = [email.strip().lower() for email in raw_emails if email]
print(cleaned_emails)
cleaned_emails = set([email.strip().lower() for email in raw_emails if email])
print(cleaned_emails)
cleaned_emails = list(dict.fromkeys(email.strip().lower() for email in raw_emails if email))
print(cleaned_emails)

['alice@example.com', 'bob@example.com', 'carol@example.com', 'bob@example.com', 'dan@example.com']
{'dan@example.com', 'alice@example.com', 'carol@example.com', 'bob@example.com'}
['alice@example.com', 'bob@example.com', 'carol@example.com', 'dan@example.com']


In [55]:
# write clean_emails() so:
# It strips, lowercases, removes falsy values ("", None).
# If unique=True, preserves first occurrence only.
# If unique=False, allows duplicates.
# Returns the list.

def clean_emails(raw_emails, unique=True):
    if unique:
          cleaned = list(dict.fromkeys(email.strip().lower() for email in raw_emails if email))
          return cleaned
    else:
          cleaned = [email.strip().lower() for email in raw_emails if email]
          return cleaned
clean_emails(raw_emails, False)


['alice@example.com',
 'bob@example.com',
 'carol@example.com',
 'bob@example.com',
 'dan@example.com']

In [56]:
# BETTER

def clean_emails(raw_emails, unique=True):
    cleaned = [email.strip().lower() for email in raw_emails if email]
    if unique:
        cleaned = list(dict.fromkeys(cleaned))
    return cleaned
clean_emails(raw_emails)

['alice@example.com',
 'bob@example.com',
 'carol@example.com',
 'dan@example.com']

In [57]:
ratings = [6, 8, 10, 7, 5]
print(len(ratings))

print(f'Average rating: {sum(ratings)/len(ratings)}')
print(f'All ratings are at least 5? {all(i >= 5 for i in ratings)}')
print(f'Any perfect 10? {any(i == 10 for i in ratings)}')

5
Average rating: 7.2
All ratings are at least 5? True
Any perfect 10? True


In [58]:
employees = ["John", "Mary", "Luke", "Sophia", "Peter"]
sales = [2500, 1800, 3200, 1500, 2800]

employee_sales_pair = list(zip(employees, sales))
print(employee_sales_pair)

# Remove any employees whose sales are below 2000.
less_2k = list(filter(lambda pair: pair[1] >= 2000, employee_sales_pair))
print(less_2k)

def tier(sale):
      if sale >= 3000:
            return 'Gold'
      if sale >= 2500:
            return 'Silver'
      if sale >= 2000:
            return 'Bronze'

# assign a performance tier based on sales
tiered = list(map(lambda pair: (pair[0], tier(pair[1])), less_2k))
print(tiered)

# Produce a numbered report table
print('No  Name  Sales  Tier')

for index, (name, sale) in enumerate(less_2k, start=1):
      print(f'{index:<3} {name:<6} {sale}')

[('John', 2500), ('Mary', 1800), ('Luke', 3200), ('Sophia', 1500), ('Peter', 2800)]
[('John', 2500), ('Luke', 3200), ('Peter', 2800)]
[('John', 'Silver'), ('Luke', 'Gold'), ('Peter', 'Silver')]
No  Name  Sales  Tier
1   John   2500
2   Luke   3200
3   Peter  2800


In [59]:
students = ["Alice", "Bob", "Carol", "Dave"]
scores   = [85, 42, 90, 68]

def to_grade(s):
    if s >= 80: return "A"
    if s >= 70: return "B"
    if s >= 50: return "C"

rows = list(
    map(
        lambda pair: (pair[0], to_grade(pair[1])),
        filter(lambda pair: pair[1] >= 50, zip(students, scores))
    )
)
print(rows)

print("No  Name    Grade")
for i, (name, grade) in enumerate(rows, start=1):
    print(f"{i:<3} {name:<6} {grade}")


[('Alice', 'A'), ('Carol', 'A'), ('Dave', 'C')]
No  Name    Grade
1   Alice  A
2   Carol  A
3   Dave   C


In [60]:
products = ["Laptop", "Phone", "Tablet", "Camera", "Headphones", "Monitor"]
units_sold = [120, 300, 80, 150, 400, 60]
unit_price = [800, 500, 300, 700, 150, 200]

total_rev = [s*p for s,p in list(zip(units_sold, unit_price))]
print(total_rev)

products_rev = [(a,b) for a,b in zip(products, total_rev)]
print(products_rev)

# Remove any products with revenue below 50,000.
# less_50k = list(filter(lambda pair:pair[1]>=50000, products_rev))
less_50k = [x for x in products_rev if x[1] >= 50000]
print(less_50k)

def ranking(price):
      if price >= 100000:
            return 'Platinum'
      if price >= 50000:
            return 'Gold'
      if price >= 25000:
            return 'Silver'
      if price >= 10000:
            return 'Bronze'
      
rows = [(product, revenue, ranking(revenue)) for product, revenue in less_50k]
print(rows)

print('No    Product      Revenue    Rank')

for i, (product, revenue, rank) in enumerate(rows, start=1):
      print(f'{i:<6}{product:<13}{revenue:<11}{rank}')
      
print(f'Something {list(zip(products, units_sold, unit_price))}')

[96000, 150000, 24000, 105000, 60000, 12000]
[('Laptop', 96000), ('Phone', 150000), ('Tablet', 24000), ('Camera', 105000), ('Headphones', 60000), ('Monitor', 12000)]
[('Laptop', 96000), ('Phone', 150000), ('Camera', 105000), ('Headphones', 60000)]
[('Laptop', 96000, 'Gold'), ('Phone', 150000, 'Platinum'), ('Camera', 105000, 'Platinum'), ('Headphones', 60000, 'Gold')]
No    Product      Revenue    Rank
1     Laptop       96000      Gold
2     Phone        150000     Platinum
3     Camera       105000     Platinum
4     Headphones   60000      Gold
Something [('Laptop', 120, 800), ('Phone', 300, 500), ('Tablet', 80, 300), ('Camera', 150, 700), ('Headphones', 400, 150), ('Monitor', 60, 200)]


In [61]:
lst = [1,2,3,4,5,6]
tpp = tuple(lst)
print(sum(lst))

fruits = ["apple", "banana", "cherry"]
fruits.append("date")
print(fruits)  # ['apple', 'banana', 'cherry', 'date']


21
['apple', 'banana', 'cherry', 'date']


In [62]:
i = [1,2,3,4]
j = (9,8,7,6,5)

i.extend(j)

print(i)

[1, 2, 3, 4, 9, 8, 7, 6, 5]


In [63]:
print(i)

[1, 2, 3, 4, 9, 8, 7, 6, 5]


In [64]:
inventory = ["apple", "banana", "cherry"]

inventory.append('date')
print(inventory)
inventory.insert(1, 'kiwi')
print(inventory)
inventory.remove('banana')
print(inventory)
inventory.extend(['mango', 'pear'])
print(inventory)
inventory.sort()
print(inventory)

print(inventory.count('mango'))

['apple', 'banana', 'cherry', 'date']
['apple', 'kiwi', 'banana', 'cherry', 'date']
['apple', 'kiwi', 'cherry', 'date']
['apple', 'kiwi', 'cherry', 'date', 'mango', 'pear']
['apple', 'cherry', 'date', 'kiwi', 'mango', 'pear']
1


In [65]:
movies = [
    ("Inception", 8.8, 2010),
    ("The Matrix", 8.7, 1999),
    ("Interstellar", 8.6, 2014),
    ("The Prestige", 8.7, 2006),
    ("Memento", 8.4, 2000)
]

movies.sort(key=lambda x:x[1], reverse=True)
print(movies)

movies.sort(key=lambda x:x[2])
print(movies)

movies.sort(key=lambda x:len(x[0]))
print(movies)

movies.sort(key=lambda x:x[0][-1])
print(movies)

movies.sort(key=lambda x:x[1], reverse=True)
print(movies)

movies.sort(key=lambda x: (-x[1], x[0]))
print(movies)

for m in movies:
    print(m, "->", (-m[1], m[0]))



[('Inception', 8.8, 2010), ('The Matrix', 8.7, 1999), ('The Prestige', 8.7, 2006), ('Interstellar', 8.6, 2014), ('Memento', 8.4, 2000)]
[('The Matrix', 8.7, 1999), ('Memento', 8.4, 2000), ('The Prestige', 8.7, 2006), ('Inception', 8.8, 2010), ('Interstellar', 8.6, 2014)]
[('Memento', 8.4, 2000), ('Inception', 8.8, 2010), ('The Matrix', 8.7, 1999), ('The Prestige', 8.7, 2006), ('Interstellar', 8.6, 2014)]
[('The Prestige', 8.7, 2006), ('Inception', 8.8, 2010), ('Memento', 8.4, 2000), ('Interstellar', 8.6, 2014), ('The Matrix', 8.7, 1999)]
[('Inception', 8.8, 2010), ('The Prestige', 8.7, 2006), ('The Matrix', 8.7, 1999), ('Interstellar', 8.6, 2014), ('Memento', 8.4, 2000)]
[('Inception', 8.8, 2010), ('The Matrix', 8.7, 1999), ('The Prestige', 8.7, 2006), ('Interstellar', 8.6, 2014), ('Memento', 8.4, 2000)]
('Inception', 8.8, 2010) -> (-8.8, 'Inception')
('The Matrix', 8.7, 1999) -> (-8.7, 'The Matrix')
('The Prestige', 8.7, 2006) -> (-8.7, 'The Prestige')
('Interstellar', 8.6, 2014) -> (

In [84]:
nums = (1, 2, 3, 2)
print(nums.count(2))   # 2
print(nums.index(3))   # 2
print(nums.index(2))   

jj = [1,2,3,4,4,4,4,4,4]
print(jj.count(4))
jj.reverse()
print(jj)

2
2
1
6
[4, 4, 4, 4, 4, 4, 3, 2, 1]


In [73]:
points = (3, 7, 9, 3, 7, 3)

print(points[2])
print(points[1:5])
print(points.count(3))
print(points.index(7))
# points[0] = 10

9
(7, 9, 3, 7)
3
1


In [79]:
available = {"Book A", "Book B", "Book C", "Book D"}
borrowed = {"Book C", "Book E"}

available = available - borrowed
print(available)
print(available & borrowed)
available.update({'Book F'})
print(available)

{'Book B', 'Book A', 'Book D'}
set()
{'Book B', 'Book F', 'Book A', 'Book D'}


In [85]:
a_set = set()

In [101]:
dict = {'a':1, 'b':2}
st = {4,5,6,7,8}
print(dict.items())
st.update(dict.items())
print(st)

dict_items([('a', 1), ('b', 2)])
{('a', 1), 4, 5, 6, 7, 8, ('b', 2)}


In [136]:
students = {
    "101": {"name": "Alice", "age": 20, "grade": "A"},
    "102": {"name": "Bob", "age": 22, "grade": "B"},
    "103": {"name": "Carol", "age": 19, "grade": "C"}
}

# getting Bob's grades safely
students.get('102')['grade']

students['104'] = {"name": "Dave", "age": 21, "grade": "B"}
print(students)

students['103']['grade'] = 'B+'
print(students)

students.pop('101')
print(students)

print(list(students.items()))

{'101': {'name': 'Alice', 'age': 20, 'grade': 'A'}, '102': {'name': 'Bob', 'age': 22, 'grade': 'B'}, '103': {'name': 'Carol', 'age': 19, 'grade': 'C'}, '104': {'name': 'Dave', 'age': 21, 'grade': 'B'}}
{'101': {'name': 'Alice', 'age': 20, 'grade': 'A'}, '102': {'name': 'Bob', 'age': 22, 'grade': 'B'}, '103': {'name': 'Carol', 'age': 19, 'grade': 'B+'}, '104': {'name': 'Dave', 'age': 21, 'grade': 'B'}}
{'102': {'name': 'Bob', 'age': 22, 'grade': 'B'}, '103': {'name': 'Carol', 'age': 19, 'grade': 'B+'}, '104': {'name': 'Dave', 'age': 21, 'grade': 'B'}}
[('102', {'name': 'Bob', 'age': 22, 'grade': 'B'}), ('103', {'name': 'Carol', 'age': 19, 'grade': 'B+'}), ('104', {'name': 'Dave', 'age': 21, 'grade': 'B'})]


In [189]:
orders = {
    "order1": {
        "customer": "Alice", 
        "items": {"apple": 3, "banana": 2}
        },
    "order2": {
        "customer": "Bob", 
        "items": {"banana": 5, "orange": 4}
        },
    "order3": {
        "customer": "Carol", 
        "items": {"apple": 1, "pear": 2, "banana": 1}
        }
}

# Print out each order with the customer name and total number of items ordered.
print(orders.items())
for ord, info in orders.items():
      print(ord, info['customer'], sum(info['items'].values()))

# Find the total quantity of bananas ordered across all orders.
banana_count_per_order = [info['items']['banana'] for _, info in orders.items()]
print(banana_count_per_order)
print(sum(banana_count_per_order))

# Add a new order "order4" for "Dave" with {"apple": 2, "mango": 3}.
orders['order4'] = {'customer':'Dave', 'items':{"apple": 2, "mango": 3}}
print(orders)

# Update "order2" so that Bob’s orange count becomes 6.
orders['order2']['items']['orange'] = 6
print(orders['order2'])

# Remove "order1" completely from the orders.
orders.pop('order1')
print(orders)

# loop through and print a clean report
for ord, info in orders.items():
    print(f"{ord} - {info['customer']}: {sum(info['items'].values())} items")

dict_items([('order1', {'customer': 'Alice', 'items': {'apple': 3, 'banana': 2}}), ('order2', {'customer': 'Bob', 'items': {'banana': 5, 'orange': 4}}), ('order3', {'customer': 'Carol', 'items': {'apple': 1, 'pear': 2, 'banana': 1}})])
order1 Alice 5
order2 Bob 9
order3 Carol 4
[2, 5, 1]
8
{'order1': {'customer': 'Alice', 'items': {'apple': 3, 'banana': 2}}, 'order2': {'customer': 'Bob', 'items': {'banana': 5, 'orange': 4}}, 'order3': {'customer': 'Carol', 'items': {'apple': 1, 'pear': 2, 'banana': 1}}, 'order4': {'customer': 'Dave', 'items': {'apple': 2, 'mango': 3}}}
{'customer': 'Bob', 'items': {'banana': 5, 'orange': 6}}
{'order2': {'customer': 'Bob', 'items': {'banana': 5, 'orange': 6}}, 'order3': {'customer': 'Carol', 'items': {'apple': 1, 'pear': 2, 'banana': 1}}, 'order4': {'customer': 'Dave', 'items': {'apple': 2, 'mango': 3}}}
order2 - Bob: 11 items
order3 - Carol: 4 items
order4 - Dave: 5 items


In [190]:
data = list(range(1, 21))   # numbers 1 through 20

# Get the first 5 numbers.
first_5 = data[:5]
print(first_5)

# Get the last 5 numbers.
last_5 = data[-5:]
print(last_5)

# Get all the even numbers.
even = data[1::2]
print(even)

# Reverse the list using slicing.
rev_list = data[::-1]
print(rev_list)

# Make a copy of the list without using list() or copy()
new = data
print(data[:])

[1, 2, 3, 4, 5]
[16, 17, 18, 19, 20]
[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]
[20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]


In [195]:
words = ["apple", "banana", "cherry", "date", "fig", "grape"]

# create a list comprehension that collects all words with more than 5 letters.
mor5 = [x for x in words if len(x) > 5]
print(mor5)

# Create a generator expression that yields each word uppercased.
upp = (x.upper() for x in words)
print(list(upp))
print(list(upp))

['banana', 'cherry']
['APPLE', 'BANANA', 'CHERRY', 'DATE', 'FIG', 'GRAPE']
[]


In [207]:
words = ["strawberry", "apple", "banana", "kiwi", "cherry", "grapefruit", "fig"]
vowels = ['a', 'e', 'i', 'o', 'u']
cons_words = [x for x in words if x[0] not in vowels]
print(cons_words)

word_length = [(x, len(x)) for x in words]
print(word_length)

rev = (x[::-1] for x in words)
print(next(rev))
print(next(rev))
print(next(rev))

['strawberry', 'banana', 'kiwi', 'cherry', 'grapefruit', 'fig']
[('strawberry', 10), ('apple', 5), ('banana', 6), ('kiwi', 4), ('cherry', 6), ('grapefruit', 10), ('fig', 3)]
yrrebwarts
elppa
ananab


In [209]:
x = 10
y = x
y += 5
print(x, y)   # 10, 15  ← separate copies because ints are immutable



10 15


In [216]:
students = ["Alice", "Bob", "Carol"]

student_grades = dict.fromkeys(students, 'Not Graded')
print(student_grades)

student_grades.setdefault('Dave', 'Not Graded')
print(student_grades)

student_grades.pop('Carol')
print(student_grades)

for s, g in student_grades.items():
      print(f'{s} -> {g}')

{'Alice': 'Not Graded', 'Bob': 'Not Graded', 'Carol': 'Not Graded'}
{'Alice': 'Not Graded', 'Bob': 'Not Graded', 'Carol': 'Not Graded', 'Dave': 'Not Graded'}
{'Alice': 'Not Graded', 'Bob': 'Not Graded', 'Dave': 'Not Graded'}
Alice -> Not Graded
Bob -> Not Graded
Dave -> Not Graded


In [218]:
nums = [10, 5, 20]
print(max(nums))                          # 20
print(min(nums))                          # 5
print(max(nums, key=lambda x: -x))        # 5 (largest negative = smallest)
print(max([], default="Empty"))           # "Empty"


20
5
5
Empty


In [226]:
players = [
    ("Alice", 1200, 5),
    ("Bob", 950, 7),
    ("Carol", 1350, 4),
    ("Dave", 1200, 6),
]

max_score = max(players, key=lambda x: x[1])
print(max_score)

lowest_game_no = min(x[2] for x in players)
print(lowest_game_no)



('Carol', 1350, 4)
4


In [229]:
players = [
    ("Alice", 1200, 5),
    ("Bob", 950, 7),
    ("Carol", 1350, 4),
    ("Dave", 1200, 6),
    ("Eve", 1350, 6),
]

# 1) Sort by score (desc), then games (asc), then name (asc)
ranked = sorted(players, key=lambda x: (-x[1], x[2], x[0]))
print(ranked)

# 2) Print top 3
print("Top 3 Players")
for i, (name, score, games) in enumerate(ranked[:3], start=1):
    print(f"{i}. {name:<5} - {score} pts, {games} games")


[('Carol', 1350, 4), ('Eve', 1350, 6), ('Alice', 1200, 5), ('Dave', 1200, 6), ('Bob', 950, 7)]
Top 3 Players
1. Carol - 1350 pts, 4 games
2. Eve   - 1350 pts, 6 games
3. Alice - 1200 pts, 5 games


In [231]:
text = "banana"
print(text.count("na"))       # 2
print(text.count("a"))        # 3
print(text.count("a", 0, 3))  # 1


2
3
1


In [234]:
scores = [85, 92, 78, 92, 85, 92, 100, 85]
print(scores.count(92))
print(scores.count(100))

3
1


In [237]:
text = "abracadabra"
count = text.count('abra')
print(count)
count = text.count('a', 0, 5)
print(count)

2
2


In [244]:
from collections import Counter
basket = ["apple", "banana", "apple", "pear", "banana", "apple", "orange"]
print(len(basket))
print(Counter(basket))
print(Counter(basket).most_common(2))
print(Counter(basket)['pear'])

7
Counter({'apple': 3, 'banana': 2, 'pear': 1, 'orange': 1})
[('apple', 3), ('banana', 2)]
1


In [247]:
pin = {'1':4, '2':3}
print(Counter(pin).most_common(1))

[('1', 4)]


In [270]:
paragraph = """
Python is powerful. Python is easy to learn.
Many people love Python because it is versatile and readable.
"""

print(paragraph.count('Python'))
print(paragraph.count('p'))

splitted = [x.strip('.').lower() for x in paragraph.split()]
print(splitted)
print(Counter(splitted).most_common(2))
print(len(set(Counter(splitted))))

3
3
['python', 'is', 'powerful', 'python', 'is', 'easy', 'to', 'learn', 'many', 'people', 'love', 'python', 'because', 'it', 'is', 'versatile', 'and', 'readable']
[('python', 3), ('is', 3)]
14


In [279]:
import numpy as np

print(np.zeros((2,3)))      # 2x3 of zeros
print(np.ones((3,3)))       # 3x3 of ones
print(np.arange(0, 10))  # [0, 2, 4, 6, 8]
print(np.linspace(0, 1, 5)) # 5 numbers evenly spaced between 0 and 1
print(np.eye(3))            # 3x3 identity matrix


[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[0 1 2 3 4 5 6 7 8 9]
[0.   0.25 0.5  0.75 1.  ]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [286]:
import numpy as np

scores = np.array([
    [85, 92, 78],   # Alice
    [88, 79, 93],   # Bob
    [72, 95, 80],   # Carol
    [91, 85, 89],   # Dave
    [77, 90, 86]    # Eve
])

print("Shape:", scores.shape)
print("Dimensions:", scores.ndim)

print("Average per student:", np.mean(scores, axis=1))
print("Average per subject:", np.mean(scores, axis=0))

print("Highest score:", np.max(scores))

scores[:,1] += 5  # bonus to Science
print("With bonus:", scores)

print("Std dev of all scores:", np.std(scores))


Shape: (5, 3)
Dimensions: 2
Average per student: [85.         86.66666667 82.33333333 88.33333333 84.33333333]
Average per subject: [82.6 88.2 85.2]
Highest score: 95
With bonus: [[ 85  97  78]
 [ 88  84  93]
 [ 72 100  80]
 [ 91  90  89]
 [ 77  95  86]]
Std dev of all scores: 7.607014306984486
